apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: manage-deployments
rules:
  - apiGroups: [ apps ]
    resources: [ deployments ]
    verbs: [ create, list, get, update, delete ]
