apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: manage-deployments
  namespace: my-project-dev
rules:
  - apiGroups: [ apps ]
    resources: [ deployments ]
    verbs: [ create, list, get, update, delete ]
